/** @type {import('@react-router/dev/config').Config} */
export default {
  ssr: false,
  prerender: [
    "/",
    "/ar/",
    "/ar/about/",
    "/ar/products/",
    "/ar/products/hot-water-cylinders/",
    "/ar/products/r290-sk16/",
    "/ar/products/r290-sk22/",
    "/ar/products/sk22/",
    "/ar/products/sk30/",
    "/ar/contact/",
    "/ar/manufacturer-documents/",
    "/ar/heat-pumps/",
    "/ar/underfloor-heating/",
    "/en/",
    "/en/about/",
    "/en/products/",
    "/en/products/hot-water-cylinders/",
    "/en/products/r290-sk16/",
    "/en/products/r290-sk22/",
    "/en/products/sk22/",
    "/en/products/sk30/",
    "/en/contact/",
    "/en/manufacturer-documents/",
    "/en/heat-pumps/",
    "/en/underfloor-heating/",
  ],
  routeDiscovery: { mode: "initial" },
};
