export const intakeCopy = {
  ar: {
    initializing: "جارٍ تجهيز نموذج الطلب…",
    intro: "أرسل طلبك مباشرة إلى فريق غولد؛ لا يلزم إنشاء حساب.",
    description: "وصف المبنى أو ملاحظات (اختياري)",
    descriptionHint: "مثلاً: الطابق، حالة البناء أو نظام التدفئة الحالي. لا ترسل معلومات شخصية غير لازمة.",
    phoneHint: "مفتاح سوريا +963؛ يمكنك استبداله بمفتاح أي بلد أو إدخال رقم سوري محلي.",
    plan: "مخطط المشروع PDF (اختياري)",
    planHint: "ملف واحد حتى 15 ميبيبايت. أرفق فقط ما يخص طلبك ويحق لك مشاركته.",
    removePlan: "إزالة المخطط",
    consent: "أوافق على حفظ هذه المعلومات واستخدامها لدى فريق غولد لدراسة طلبي والتواصل معي بشأنه.",
    consentWithPlan: "أوافق على حفظ هذه المعلومات والمخطط إن أرفقته، واستخدامها لدى فريق غولد لدراسة طلبي والتواصل معي بشأنه.",
    privacy: "هذه موافقة لمعالجة الطلب فقط، وليست اشتراكاً برسائل تسويقية. يمكنك الاستفسار عن بيانات طلبك عبر وسائل التواصل الرسمية أدناه.",
    send: "إرسال الطلب",
    sending: "جارٍ إرسال الطلب…",
    verifying: "جارٍ التحقق الآمن…",
    success: "تم استلام طلبك",
    successBody: "حُفظ طلبك لدى فريق غولد. احتفظ بالمرجع التالي للمتابعة؛ لا تحتاج إلى إرساله مرة أخرى.",
    reference: "مرجع الطلب",
    another: "إرسال طلب آخر",
    unavailableTitle: "إرسال الطلبات غير متاح حالياً",
    unavailable: "يمكنك التواصل مباشرة مع فريق غولد عبر الهاتف أو البريد.",
    call: "اتصل بالفريق",
    email: "راسلنا بالبريد",
    offline: "أنت غير متصل. معلوماتك باقية في هذه الصفحة؛ أعد المحاولة عند عودة الاتصال.",
    errorTitle: "لم يكتمل تأكيد الطلب",
    unconfirmed: "تعذّر تأكيد الاستلام. أبقِ هذه الصفحة مفتوحة وأعد المحاولة بنفس المعلومات؛ سنستخدم مرجع الإرسال نفسه لتجنب التكرار.",
    validation: "راجع الحقول المحددة ثم أعد الإرسال. لم نحذف معلوماتك.",
    challenge: "لم يكتمل التحقق الآمن. أعد المحاولة لتجديده، أو تواصل مع الفريق مباشرة.",
    rate_limit: "وصلت محاولات كثيرة خلال وقت قصير. انتظر قليلاً ثم أعد المحاولة؛ معلوماتك محفوظة في هذه الصفحة.",
    conflict: "تعذّر مطابقة هذه المحاولة مع الطلب السابق. لا تكرر الإرسال؛ تواصل مع الفريق للتحقق من وصول طلبك.",
    fields: {
      name: "أدخل الاسم، حتى 255 حرفاً.",
      phone: "تحقق من رقم التواصل ومفتاح البلد.",
      location: "أدخل عنوان المشروع، حتى 500 حرف.",
      area_sqm: "أدخل مساحة أكبر من صفر وحتى 1,000,000 م².",
      description: "اختصر الوصف إلى 3000 حرف أو أقل.",
      consent: "تلزم موافقتك لمعالجة هذا الطلب.",
      plan: "اختر ملف PDF صالحاً وغير فارغ، بحجم لا يتجاوز 15 ميبيبايت.",
      turnstile_token: "أعد الإرسال لإجراء تحقق آمن جديد.",
    },
  },
  en: {
    initializing: "Preparing the request form…",
    intro: "Send your request directly to the GOLD team. No account is required.",
    description: "Building description or notes (optional)",
    descriptionHint: "For example: floor, construction stage or existing heating. Do not include unnecessary personal information.",
    phoneHint: "Syria defaults to +963. Replace it with any country code, or enter a local Syrian number.",
    plan: "Project plan PDF (optional)",
    planHint: "One file, up to 15 MiB. Share only material relevant to this request that you are entitled to share.",
    removePlan: "Remove plan",
    consent: "I agree that GOLD may store these details to assess my request and contact me about it.",
    consentWithPlan: "I agree that GOLD may store these details and any attached plan to assess my request and contact me about it.",
    privacy: "This permission covers your request only, not marketing messages. Contact us through the official channels below with questions about your request data.",
    send: "Send request",
    sending: "Sending request…",
    verifying: "Completing security check…",
    success: "Your request has been received",
    successBody: "Your request is saved with the GOLD team. Keep the reference below for follow-up; you do not need to send it again.",
    reference: "Request reference",
    another: "Send another request",
    unavailableTitle: "Request submission is currently unavailable",
    unavailable: "You can contact the GOLD team directly by phone or email.",
    call: "Call the team",
    email: "Email us",
    offline: "You are offline. Your information is still on this page. Retry when your connection returns.",
    errorTitle: "Your request is not yet confirmed",
    unconfirmed: "We could not confirm receipt. Keep this page open and retry with the same information; the same submission key will be reused to avoid duplicates.",
    validation: "Review the highlighted fields and send again. Your information has not been cleared.",
    challenge: "The security check did not complete. Retry to renew it, or contact the team directly.",
    rate_limit: "There have been too many attempts recently. Wait a little before retrying. Your information is still on this page.",
    conflict: "This attempt could not be matched to the earlier request. Do not resend; contact the team to check whether it arrived.",
    fields: {
      name: "Enter a name of up to 255 characters.",
      phone: "Check the contact number and country code.",
      location: "Enter the project address, up to 500 characters.",
      area_sqm: "Enter an area greater than zero and no more than 1,000,000 m².",
      description: "Keep the description to 3,000 characters or fewer.",
      consent: "Your permission is required to process this request.",
      plan: "Choose a valid, non-empty PDF no larger than 15 MiB.",
      turnstile_token: "Send again to complete a new security check.",
    },
  },
};
